source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'pg'

group :assets do
  gem 'sprockets-rails', '~> 2.0.0'
  gem 'sass-rails', '~> 4.0.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
end

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'cancan', '1.6.9'

group :test, :development do
  gem 'rspec-rails', "~> 2.13.2"
end

group :test do
  gem 'capybara', "2.0.2"
  gem 'factory_girl_rails', '4.2.1'
  gem 'factory_girl', '4.2.0'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

